# Generated by Django 4.1.7 on 2023-03-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
