# Generated by Django 4.1.7 on 2023-03-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_class_person_student_remove_todolist_user_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Class",
            new_name="Classe",
        ),
    ]
